- id: dart-format
  name: Dart source code format
  entry: dart format
  language: system
  args: ["--output=none", "--set-exit-if-changed"]
  types: [dart]
- id: dart-analyze
  name: Analyze Dart code
  entry: dart analyze
  language: system
  args: ["--fatal-infos", "--fatal-warnings"]
  files: (\.dart|pubspec\.yaml)$
